version: '3'

services:
      
  career-mgr-hiring:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
      
  career-spec-hiring:
    build: 
      context: .
      dockerfile: Dockerfile.spec
    ports:
      - "3051:3051"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  database-hiring:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db_data_hiring:/var/lib/postgresql/data
      
  chrome-hiring:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5905:5905"
      
  redis-hiring:
    image: redis
    
  redis-spec-hiring:
    image: redis

volumes:
  db_data_hiring:
