version: '3'

services:
      
  career-mgr:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
      
  career-spec:
    build: 
      context: .
      dockerfile: Dockerfile.spec
    ports:
      - "3051:3051"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  database:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db-data:/var/lib/postgresql/data
      
  chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5905:5905"
      
  redis:
    image: redis
    
  redis-spec:
    image: redis

volumes:
  db-data:
